Mapa de la pobreza
========================================================

```{r}
library(gridExtra)
library(maptools)
library(ggplot2)
library(plyr)
library(rgdal)
```

```{r}
load("./data/pobreza.Rda")
```

```{r}
#colmap <- readShapePoly(fn="./mapas_colombia/COL_adm1.shp")
colmap <- readOGR(dsn="./otro_mapa/", layer="COL_adm1")
colmapdf <- fortify(colmap)
```

## Por municipios

```{r fig.width=12, fig.height=15}

th <- theme(axis.text.x = element_blank(), 
            axis.text.y = element_blank(), 
            axis.ticks= element_blank(),
            axis.title=element_blank(),
            panel.grid.major=element_blank(), 
            panel.grid.minor=element_blank(), 
            plot.background=element_blank(), 
             panel.background=element_blank()
#             panel.border=element_blank()
            )

m <- ggplot(data=colmapdf)
m <- m + geom_path(aes(x=long, y=lat, group=group), color="grey") + coord_equal() +th
m <- m + geom_point(aes(x = Longitud, y = Latitud, color = NivelesIncidencia), data = pobreza, alpha = .9)
m <- m + scale_colour_discrete(name = "Incidencia de\n Pobreza", labels=c("<36%", "36%<x<57%", "57%<x<78%", ">78%"))
m

ggsave("./figure/mapa_municipios.png", m, width=12, height=15)
```

## Por departamento


```{r}


colmap@data$id <- rownames(colmap@data)
departamentos.df <- fortify(colmap)
departamentos.df <- join(departamentos.df, colmap@data, by="id")
#departamentos.df$NAME_1 <- mapvalues(departamentos.df$NAME_1, from=c("Atl\xe1ntico", "Choc\xf3", "C\xf3rdoba", "Vaup\xe9s", "Bol\xedvar", "San Andr\xe9s y Providencia", "Boyac\xe1", "Caquet\xe1", "Guain\xeda","Nari\xf1o", "Quind\xedo"), to =c("Atlántico", "Chocó", "Córdoba", "Vaupés", "Bolívar", "San Andrés y Providencia", "Boyacá", "Caquetá", "Guainía","Nariño", "Quindío"))
pobreza_depto <- ddply(pobreza,~Departamento,summarise,mean=mean(Incidencia))
pobreza_depto$Departamento <- mapvalues(pobreza_depto$Departamento, from = c("C/marca.", "Norte de Sant.", "San Andrés, Prov. y Sta Cat.", "Valle", "Guajira"), to=c("Cundinamarca", "Norte de Santander", "San Andrés y Providencia", "Valle del Cauca", "La Guajira"))
pobreza_depto <- pobreza_depto[-5,]

departamentos.df <- merge(departamentos.df, pobreza_depto, by.x="NAME_1", by.y="Departamento", all.x=T, all.y=F)
```


```{r fig.width=12, fig.height=15}

mapa_pobreza <- ggplot(data=departamentos.df, aes(x=long, y=lat, group=group)) + th
mapa_pobreza <- mapa_pobreza + geom_polygon(aes(fill=mean))
mapa_pobreza <- mapa_pobreza + geom_path(color="white", linestyle=2, aes(group=group))
mapa_pobreza <- mapa_pobreza + coord_equal()
mapa_pobreza <- mapa_pobreza + scale_fill_gradient(name="Promedio de incidencia\nde pobreza por\ndepartamento",
                                                   low="#ffffcc", high="#ff4444", 
                                                    space="Lab", na.value="grey50",
                                                    guide="colourbar")
mapa_pobreza <- mapa_pobreza + labs(title="Pobreza por departamento")

mapa_pobreza

ggsave("./figure/mapa_departamentos.png", mapa_pobreza, width=12, height=15)
```

## Otra versión del mapa de municipios

```{r}
# Estos shapefiles son mejores que los que usé en el mapa de arriba. 
deptos <- readOGR(dsn="./depto/", layer="depto")
levels(deptos@data$DPTO) <- as.numeric(levels(deptos@data$DPTO))
deptos@data$id <- rownames(deptos@data)
deptos.df <- fortify(deptos)

municipios <- readOGR(dsn="./mpio/", layer="mpio")
municipios@data$id <- rownames(municipios@data)
municipios@data$codigo_municipio <- as.numeric(gsub(" ", "", paste(municipios@data$DPTO, municipios@data$MPIO)))
municipios.data <- merge(municipios@data, pobreza, by.x="codigo_municipio", by.y="Código.Municipio", all.x=T, all.y=F)
municipios.df <- fortify(municipios)
municipios.df <- join(municipios.df, municipios.data, by="id")
```

```{r}
p <- ggplot(data=municipios.df, aes(x=long, y=lat, group=group)) + coord_equal() + th
p <- p + geom_path(color="white")
p <- p + geom_polygon(aes(fill=Incidencia))
p <- p + scale_fill_gradient(name="Incidencia de Pobreza",
                               low="#7c0c0c", high="#9d9999", 
                               space="Lab", na.value="grey90",
                               guide="colourbar")
p <- p + geom_path(color="white", data=deptos.df, size= 0.1,  aes(x=long, y=lat, group=group))
p
```

```{r}
antioquia.df <- subset(municipios.df, municipios.df$DPTO == "05")
cundinamarca.df<-subset(municipios.df, municipios.df$DPTO == "25")
valle.df<-subset(municipios.df, municipios.df$DPTO == "76")
```

```{r}
pa <- ggplot(data=antioquia.df, aes(x=long, y=lat, group=group)) + coord_equal() + th
pa <- pa + geom_path(color="white")
pa <- pa + geom_polygon(aes(fill=Incidencia))
pa <- pa + scale_fill_gradient(name="Incidencia de Pobreza",
                               low="#7c0c0c", high="#9d9999", 
                               space="Lab", na.value="grey90",
                               guide="colourbar")
#p <- p + geom_path(color="white", data=deptosdf, size= 0.1,  aes(x=long, y=lat, group=group))
pa
```

```{r}
pc <- ggplot(data=cundinamarca.df, aes(x=long, y=lat, group=group)) + coord_equal() + th
pc <- pc + geom_path(color="white")
pc <- pc + geom_polygon(aes(fill=Incidencia))
pc <- pc + scale_fill_gradient(name="Incidencia de Pobreza",
                               low="#7c0c0c", high="#9d9999", 
                               space="Lab", na.value="grey90",
                               guide="colourbar")
#p <- p + geom_path(color="white", data=deptosdf, size= 0.1,  aes(x=long, y=lat, group=group))
pc
```

```{r}
pv <- ggplot(data=valle.df, aes(x=long, y=lat, group=group)) + coord_equal() + th
pv <- pv + geom_path(color="white")
pv <- pv + geom_polygon(aes(fill=Incidencia))
pv <- pv + scale_fill_gradient(name="Incidencia de Pobreza",
                               low="#7c0c0c", high="#9d9999", 
                               space="Lab", na.value="grey90",
                               guide="colourbar")
#p <- p + geom_path(color="white", data=deptosdf, size= 0.1,  aes(x=long, y=lat, group=group))
pv
```

```{r}
ggsave("./figure/pobreza_municipios_valle.png", pv, width=15, height=15)
ggsave("./figure/pobreza_municipios_cundinamarca.png", pc, width=15, height=15)
ggsave("./figure/pobreza_municipios_antioquia.png", pa, width=15, height=15)
ggsave("./figure/pobreza_municipios.png", p, width=12, height=15)
```

```{r}
tres <- arrangeGrob(pa,pc,pv, nrow=3)
ggsave("./figure/tres_departamentos.png", tres, width=12, height=36)
```